version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - .:/app # map local files to container /app dir (live updating)
      - /app/node_modules # bookmark volume; don't map from container to local
