name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Docker compose up in background
      run: docker-compose up -d
      
      
    - name: Lint
      run: docker-compose exec -T web yarn lint

      
    - name: Run tests
      run: docker-compose exec -e CI=true -T web yarn test
